### ISSUE TITLE
feature request: conda install

### ISSUE THREAD

**Issue by shimwell** [LiamPattinson/proper_tea#8]
Hi @LiamPattinson 

I'm currently adding conda installs for all the packages in the [neutronics workflow](https://user-images.githubusercontent.com/8583900/150701623-29fbf50b-0203-4818-b318-2f3a996e1db7.png)

One of the tricky parts of doing this is that all dependencies also need to have conda installs.

So I was just wondering if you have any plans for a proper_tea conda install?

I've been looking into automating the process of making conda installs and it appears there is a [github action](https://github.com/m0nhawk/conda-package-publish-action) that has been adapted on [several forks](https://github.com/m0nhawk/conda-package-publish-action/network/members) to allow more flexibility.

Some forks add the ability to push to custom channels, others allow additional OS to be supported. I can't find one fork that does everything.

**Comment by shimwell** [comment]
I am working on automating the conda release over on the stl-to-h5m repo if there is anything of use.
https://github.com/fusion-energy/stl_to_h5m/pull/9

I would be happy to make a PR here. I think we would need the following

- [ ] /conda/meta.yml
- [ ] /.github/workflows/anaconda-publish.yml

and a few other files

I've got an anaconda github action that I'm working on here if it is any use.
https://github.com/shimwell/anaconda-publish
It might be better placed in the plasmafair repo?

**Comment by LiamPattinson** [comment]
That would certainly be helpful, but I think I'll need to make some other additions before it'll be ready to publish on conda-forge. The current lack of docs means it's unlikely to pass review. The whole process also appears to be much more complicated than uploading to PyPI, so I'd like to take some time to familiarise myself with the process before proceeding much further.

**Comment by shimwell** [comment]
Conda forge has details of the method of making a package [here](https://conda-forge.org/#add_recipe) which I've done a few times so I could also help with that

**Comment by LiamPattinson** [comment]
Hi again @shimwell, I believe I've got it working. You should now be able to install using `conda install -c liampattinson proper_tea`. I couldn't get your github action to work, as it seemed to not like this line:

https://github.com/shimwell/anaconda-publish/blob/a785b02fa0f96c7b7604af468e2161aefb5695c7/entrypoint.sh#L35

As I'm only making a 'noarch' package, it didn't like the reference to the `linux-64` directory. It might be worth adding an if statement to check whether the noarch or linux-64 directories exist before calling upload.

It took me a while to work out all the bugs, but I was able to get this working in my own workflow, which runs alongside a PyPI upload:

https://github.com/LiamPattinson/proper_tea/blob/617a4916db0b4a0e63fa14f80eec35c6f9acc74e/.github/workflows/publish.yml#L35-L56

I suspect the python setup step is unnecessary, but I'm leaving it in for now as it isn't causing any harm. I'll work on getting it onto conda-forge at some point in the near future, but I'll need to add some new features, add some docs, and improve my unit tests first.

**Comment by shimwell** [comment]
Amazing, nice work. I shall have a go at downloading it.

By the way it looks like you have two `vv` in the version number https://anaconda.org/liampattinson/proper_tea

**Comment by shimwell** [comment]
Your publsh github action looks very nice and concise, I'm not sure how it gets the channel name but perhaps that is linked to the anaconda token?

**Comment by shimwell** [comment]
```conda install -c liampattinson proper_tea``` works and I was able to import it after downloading it.

Nice work, shall we close this issue or keep it open for the conda-forge version

**Comment by LiamPattinson** [comment]
> By the way it looks like you have two `vv` in the version number https://anaconda.org/liampattinson/proper_tea

Hmm, that's frustrating. It seems that setuptools_scm and github prefer v0.0.0, while anaconda would prefer just 0.0.0. I got automatic version inference working in my meta.yaml, but it might need some further work to remove the 'v' from the git tags.

> Your publsh github action looks very nice and concise, I'm not sure how it gets the channel name but perhaps that is linked to the anaconda token?

As it's just going to my own channel, I think the API token is sufficient. I'm not sure if it's possible to upload to multiple channels without using `anaconda upload`, but I couldn't get that command to work from within actions.

I'll close this issue for now, and perhaps raise a new issue for conda-forge.
